Repository Dr-Pong/dr_pong_client, pull requests merged in 2023-08, with the labels that each got.

#507 [feat] 내가 만든 404 페이지 #501
  locales/en/common.json
  locales/ko/common.json
  pages/404.tsx
  styles/custom404/Custom404.module.scss
Labels: feat

#506 [fix] 게임 결과 페이지 사소한 문제점들 해결하기 + 게임이모지 조금 수정 #504
  components/game/result/GameResultDetail.tsx
  components/game/result/LpProgressBar.tsx
  i18n.json
  styles/game/Emojis.module.scss
  styles/game/Game.module.scss
  styles/records/Player.module.scss
  types/userTypes.ts
Labels: fix

#509 [fix] 디엠에 접근 불가능한 이슈 #508
  components/chats/ChatsFrame.tsx
Labels: fix

#510 [feat] footer 추가하기 #505
  components/records/LadderPoint.tsx
  locales/en/records.json
  locales/ko/records.json
  pages/channels.tsx
  pages/friends.tsx
  pages/leaderboard.tsx
  pages/myPage.tsx
  pages/records/[[...nickname]].tsx
  styles/layouts/Footer.module.scss
  styles/records/MatchDetail.module.scss
  styles/records/Player.module.scss
  styles/records/RecordBox.module.scss
  styles/records/RecordList.module.scss
Labels: feat

#512 [feat] settings에 인포 추가 및 푸터에 깃링크 추가 close #511
  components/layouts/Footer.tsx
  components/settings/Settings.tsx
  styles/layouts/Footer.module.scss
  styles/settings/Settings.module.scss
Labels: feat

#514 [fix] 엘피 화살표 삐져나가지 않게 해요 #513
  components/game/result/LpProgressBar.tsx
  hooks/useAuthHandler.ts
Labels: fix

#518 [fix] 배포하고 찾은 수정사항들 #516
  components/global/GoogleAd.tsx
  components/layouts/AdsLayout.tsx
  components/myPage/AchievementModalPart.tsx
  styles/myPage/AchievementModalPart.module.scss
Labels: fix

#519 [feat] 브라우저에 보일 타이틀 넣기 #517
  pages/_document.tsx
Labels: feat

#521 [fix] 인풋창 줌 방지하기 #520
  pages/_document.tsx
Labels: fix

#524 [fix] 조이스틱 방식에서 터치 방식으로 조작 변경 #522
  components/game/Emojis.tsx
  components/game/PongGame.tsx
  components/joystick/Joystick.tsx
  locales/en/guide.json
  locales/ko/guide.json
  package.json
  styles/game/Emojis.module.scss
  styles/game/Game.module.scss
  styles/game/PongGame.module.scss
Labels: fix

#532 [style] hover 너는 모냐..? #529
  styles/channels/ChannelBox.module.scss
  styles/channels/MyChannel.module.scss
  styles/channels/ParticipantBox.module.scss
  styles/game/Emojis.module.scss
  styles/game/GameButtons.module.scss
  styles/global/Button.module.scss
  styles/global/Pagination.module.scss
  styles/index/Home.module.scss
  styles/layouts/NavigationBar.module.scss
  styles/myPage/StatusMessage.module.scss
Labels: fix, style

#538 [fix] 모바일에서 채팅 인풋창 포커스 아웃 #533
  components/chats/ChatInputBox.tsx
Labels: fix
