Repository Dr-Pong/dr_pong_client, pull requests merged in 2023-09, with the labels that each got.

#539 [fix] 스크롤 리멤버 #534
  styles/common.scss
  styles/layouts/Layout.module.scss
Labels: fix

#540 [delete] 티어는 없어~ close #535
  components/myPage/AchievementModalPart.tsx
  components/myPage/profile/BestRecord.tsx
  components/myPage/profile/RankTag.tsx
  components/myPage/profile/StatCard.tsx
  components/myPage/profile/TierLp.tsx
  hooks/useUpperModalProvider.tsx
  locales/en/myPage.json
  locales/ko/myPage.json
  styles/myPage/AchievementModalPart.module.scss
  styles/myPage/BestRecord.module.scss
  styles/myPage/RankTag.module.scss
  styles/myPage/StatCard.module.scss
  styles/myPage/TierLp.module.scss
  styles/myPage/WinRateStat.module.scss
Labels: delete

#543 [fix] 게임 종료 후 메인으로 돌아갈 때 어치브먼트 토스트 꺼주기 #542
  components/game/PongFrame.tsx
  components/game/PongGame.tsx
Labels: fix

#544 [style] game instruction close #531
  components/game/GameGuide.tsx
  components/global/PetitPagination.tsx
  hooks/useModalProvider.tsx
  pages/game/index.tsx
  styles/channels/ChannelsFrame.module.scss
  styles/channels/MyChannel.module.scss
  styles/game/GameGuide.module.scss
  styles/global/Pagination.module.scss
  styles/layouts/AdsLayout.module.scss
  styles/myPage/StatCard.module.scss
Labels: style

#545 [refactor] 우리 로딩하는거 티내지 말자 #463
  components/channels/ChannelsFrame.tsx
  components/channels/participants/Participants.tsx
  components/directMessages/DirectMessages.tsx
  components/friends/FriendTabContents.tsx
  components/game/Emojis.tsx
  components/global/InvitationFrame.tsx
  components/global/LoadingSpinner.tsx
  components/global/QueueSpinner.tsx
  components/global/UserImages.tsx
  components/layouts/LoginFilter.tsx
  components/layouts/header/DirectMessageButton.tsx
  components/leaderboard/BottomLeaders.tsx
  components/leaderboard/TopLeaders.tsx
  components/myPage/SelectTab.tsx
  components/myPage/profile/Profile.tsx
  components/notifications/FriendRequestsBox.tsx
  components/notifications/InvitationList.tsx
  components/settings/BgmField.tsx
  components/settings/SoundEffectField.tsx
  components/settings/TfaField.tsx
  hooks/useChatQuery.ts
  package-lock.json
  styles/global/ErrorRefresher.module.scss
  styles/global/InvitationFrame.module.scss
  styles/global/LoadingSpinner.module.scss
  styles/global/QueueSpinner.module.scss
  styles/global/UserImages.module.scss
  styles/leaderboard/TopLeaders.module.scss
  types/chatTypes.ts
Labels: refactor

#550 [fix] 쿠키 유효기간 하루로 바꾸기 #548
  hooks/useAuthHandler.ts
Labels: fix

#551 [fix] 래더 게임 Lp 결과 화면이 바뀌었습니다. #541
  components/game/result/GameResultDetail.tsx
  components/game/result/LpProgressBar.tsx
  components/game/result/LpResultBar.tsx
  styles/game/result/LpProgressBar.module.scss
Labels: fix

#549 [feat] 게임 렉을 어느정도 해소했습니다.. #537
  components/game/GameCanvas.tsx
  types/gameTypes.ts
Labels: feat

#553 [feat] 시즌 이름 보여주기 #552
  components/leaderboard/SeasonGuide.tsx
  components/leaderboard/SeasonTitle.tsx
  hooks/useModalProvider.tsx
  i18n.json
  locales/en/season.json
  locales/ko/season.json
  pages/api/seasons/current.ts
  pages/leaderboard.tsx
  styles/leaderboard/SeasonGuide.module.scss
  styles/leaderboard/SeasonTitle.module.scss
Labels: feat

#555 [feat] 스핀 소리 넣기 #554
  components/game/PongFrame.tsx
  hooks/useSoundEffect.ts
  public/sound/bar_hit.mp3
  public/sound/spin.mp3
  public/sound/touch.mp3
  styles/custom404/Custom404.module.scss
Labels: feat

#558 [fix] 채널 입장시 비밀번호 에 오토포커스 #556
  components/channels/PasswordSubmit.tsx
  components/channels/channelSettings/PasswordInput.tsx
  locales/en/channels.json
  locales/ko/channels.json
Labels: fix

#560 [style] 승률 게이지랑 버튼 정렬 수정 #547
  components/friends/FriendButtons.tsx
  components/global/UserBox.tsx
  components/myPage/profile/WinRateStat.tsx
  styles/global/UserBox.module.scss
  styles/myPage/WinRateStat.module.scss
Labels: style

#562 [feat & fix] 파비콘 더하고 타이틀 옮기기 #561
  pages/_app.tsx
  pages/_document.tsx
  public/image/drpong_favicon.svg
Labels: fix, feat

#566 [style] 여백 줄이기 #565
  styles/leaderboard/Leaderboard.module.scss
  styles/leaderboard/SeasonTitle.module.scss
Labels: style

#564 [fix] 프로필 에딧 문제 긴급 해결.. #563
  components/myPage/SelectTab.tsx
  components/myPage/profile/Profile.tsx
Labels: fix

#570 [fix] 게스트 모드 채널 생성 막기 #569
  components/channels/ChannelFilter.tsx
Labels: fix

#571 [fix] z-index 제거하기 #547
  components/myPage/profile/WinRateStat.tsx
Labels: fix

#574 [feat] 매치 성사 소리 #573
  components/game/GameLobby.tsx
  hooks/useSoundEffect.ts
  public/sound/game_start.mp3
  public/sound/spin.mp3
Labels: feat

#576 [fix] 시즌 설명 문구 추가 #575
  locales/en/season.json
  locales/ko/season.json
Labels: fix

#580 [fix] 여러판 할 때 잔상이 안 남는 문제 해결과 게임 매치 사운드 래더에서도 나게 #578
  components/game/GameCanvas.tsx
  pages/game/index.tsx
Labels: fix

#582 [deploy] 1.0.2 배포
  components/game/GameCanvas.tsx
  pages/game/index.tsx
  styles/chats/ChatBox.module.scss
Labels: deploy

#584 [fix] 폰트 바꿈 #583
  styles/common.scss
  styles/globals.css
Labels: fix
